In [12]:
import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname,filename))

In [13]:
df = pd.read_csv(r"D:\Downloads\heart_cleveland_upload.csv")

In [14]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [17]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [18]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\sumit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [19]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.85
Accuracy of Decision Trees 0.75

In [21]:
confusion_matrix(y_test,y_pred1)

array([[27,  1],
       [ 8, 24]], dtype=int64)

In [23]:
print("logistic regression confusion matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

logistic regression confusion matrix

    0   1
0  27   1
1   8  24

In [24]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  23   5
1  10  22

In [26]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [27]:
result.shape

(60, 3)

In [28]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
206             1                               1                         1
126             1                               1                         0
94              0                               0                         1
164             1                               1                         0
221             1                               1                         1
170             1                               1                         1
230             1                               1                         1
89              0                               0                         0
179             1                               1                         1
173             1                               1                         0

In [29]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [30]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  27   1
1   8  24
--------------------------------------------------
Precision -  0.96
Recall -  0.75
F1 score -  0.8421052631578947

In [31]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  23   5
1  10  22
--------------------------------------------------
Precision -  0.8148148148148148
Recall -  0.6875
F1 score -  0.7457627118644068

In [34]:
precision_score(y_test,y_pred1,average=None)

array([0.77142857, 0.96      ])

In [35]:
precision_score(y_test,y_pred2,average=None)

array([0.6969697 , 0.81481481])

In [36]:
recall_score(y_test,y_pred2,average=None)

array([0.82142857, 0.6875    ])